version: '3'
services:
  blablah-redis-server: 
    image: 'redis'
  blablah-nginx-webserver: 
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/blablah.app/fullchain.pem:/etc/letsencrypt/live/blablah.app/fullchain.pem
      - /etc/letsencrypt/live/blablah.app/privkey.pem:/etc/letsencrypt/live/blablah.app/privkey.pem
    ports:
      - 80:80
      - 443:443
  # Nodejs ExpressJs Socket.io app to server chat session
  blablah-node-app:
    build: .
    ports:
      - "8000:8000"
# volumes:
#   umami-db-data: