# This is a basic workflow to help you get started with Actions

name: Deploy BlaBlah to DigitalOcean Droplet

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ release ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploy to DigitalOcean Droplet via github SSH actions
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: appleboy/ssh-action@v0.1.3
        with: 
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            #this deployment gives little downtime on app
            #stop all the running containers
            docker kill $(docker ps -q)
            
            #remove all containers
            docker rmi $(docker images -q)
            
            rm -rf blablah-frontend
            git clone https://github.com/omkarajagunde/blablah-frontend.git
            cd blablah-frontend
            
            docker-compose up --build
